# Generated by Django 5.2.6 on 2025-10-10 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания доступа')),
                ('full_set_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за весь комплект')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка альбома (необязательно)')),
                ('is_grouping', models.BooleanField(default=False, help_text='Отметьте, если в этом альбоме будут только другие альбомы, а не фотографии.', verbose_name='Это родительский альбом (для группировки)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_albums', to='gallery.album', verbose_name='Родительский альбом')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/originals/', verbose_name='Оригинальное фото')),
                ('processed_image', models.ImageField(blank=True, editable=False, null=True, upload_to='photos/processed/', verbose_name='Обработанное фото (для показа)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
