# Generated by Django 6.0 on 2026-02-04 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupingAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название папки')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Access Token')),
                ('is_grouping', models.BooleanField(default=True, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия доступа')),
                ('full_set_price', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10, verbose_name='Цена за весь комплект')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_albums', to='gallery.groupingalbum', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
            ],
            options={
                'verbose_name': 'Все объекты (Служебное)',
                'verbose_name_plural': 'Все объекты (Служебное)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.groupingalbum',),
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
            ],
            options={
                'verbose_name': 'Альбом с фото',
                'verbose_name_plural': 'Альбомы с фото',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.groupingalbum',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/originals/', verbose_name='Оригинальное фото')),
                ('processed_image', models.ImageField(blank=True, editable=False, null=True, upload_to='photos/processed/', verbose_name='Превью (с водяным знаком)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('album', models.ForeignKey(limit_choices_to={'is_grouping': False}, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.photoalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
