# Generated by Django 6.0 on 2026-02-05 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupingalbum',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_grouping': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_albums', to='gallery.groupingalbum', verbose_name='Родительская папка'),
        ),
    ]
