# Generated by Django 5.2.6 on 2025-10-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupingAlbum',
            fields=[
            ],
            options={
                'verbose_name': 'Альбом (с альбомами)',
                'verbose_name_plural': 'Альбомы (с альбомами)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.album',),
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
            ],
            options={
                'verbose_name': 'Альбом (с фото)',
                'verbose_name_plural': 'Альбомы (с фото)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.album',),
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Все альбомы'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(limit_choices_to={'is_grouping': False}, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.photoalbum', verbose_name='Альбом'),
        ),
    ]
