# Generated by Django 5.2.6 on 2025-10-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_groupingalbum_photoalbum_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='full_set_price',
            field=models.DecimalField(decimal_places=2, default=2500.0, editable=False, max_digits=10, verbose_name='Цена за весь комплект'),
        ),
        migrations.AlterField(
            model_name='album',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_grouping': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_albums', to='gallery.album', verbose_name='Родительский альбом'),
        ),
    ]
