# Generated by Django 6.0 on 2026-04-07 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_groupingalbum_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAlbum',
            fields=[
            ],
            options={
                'verbose_name': 'Ребёнок (Альбом)',
                'verbose_name_plural': '3. Дети (Альбомы)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.groupingalbum',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': '2. Группы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.groupingalbum',),
        ),
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
            ],
            options={
                'verbose_name': 'Садик',
                'verbose_name_plural': '1. Садики',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.groupingalbum',),
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Все объекты', 'verbose_name_plural': 'Все объекты'},
        ),
        migrations.AlterModelOptions(
            name='groupingalbum',
            options={'verbose_name': 'Папка (Общая)', 'verbose_name_plural': 'Папки (Общие)'},
        ),
        migrations.AlterField(
            model_name='groupingalbum',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(limit_choices_to={'is_grouping': False}, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.childalbum', verbose_name='Ребёнок'),
        ),
        migrations.DeleteModel(
            name='PhotoAlbum',
        ),
    ]