# Generated by Django 6.0 on 2025-12-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_album_full_set_price_alter_album_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title'], 'verbose_name': 'Объект галереи', 'verbose_name_plural': 'Все объекты'},
        ),
        migrations.AlterModelOptions(
            name='groupingalbum',
            options={'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка (необязательно)'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_grouping',
            field=models.BooleanField(default=False, help_text='Если галочка стоит — это Папка (содержит другие альбомы). Если нет — это Альбом с фото.', verbose_name='Это папка?'),
        ),
        migrations.AlterField(
            model_name='album',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_grouping': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_albums', to='gallery.album', verbose_name='Родительская папка'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
