# Generated by Django 6.0 on 2026-04-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='productformat',
            name='is_collage',
            field=models.BooleanField(default=False, help_text='Если галочка стоит, цена будет браться только 1 раз за весь заказ.', verbose_name='Это Коллаж?'),
        ),
    ]
