# Generated by Django 5.2.6 on 2025-10-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_received_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received_bonus',
        ),
    ]
