# Generated by Django 5.2.6 on 2025-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_received_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_bonus',
            field=models.BooleanField(default=False, verbose_name='Бесплатный комплект (бонус)'),
        ),
    ]
