# Generated by Django 5.2.6 on 2025-11-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_received_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received_bonus',
            field=models.BooleanField(default=False, verbose_name='Бонус получен?'),
        ),
    ]
