# Generated by Django 6.0 on 2025-12-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_received_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productformat',
            name='is_collage',
            field=models.BooleanField(default=False, help_text='Если галочка стоит, цена будет браться только 1 раз за весь заказ, независимо от количества выбранных фото.', verbose_name='Это Коллаж?'),
        ),
    ]
